### ISSUE TITLE
Create basic simulation using Gazebo

### ISSUE THREAD

**Issue by JuanDelPueblo** [Rumarino-Team/hydrus-software-stack#21]
Due to the complexity of implementing our submarine on UUV simulator/Project DAVE, one alternative that needs to be explored for our simulation is using the base of the simulations directly instead, in this case Gazebo. While it may not be as accurate as the full simulation, it should still work for testing the controls and mission logic system.

Requirements:
* Run the Gazebo simulation and learn how it works
* Create a rectangular prism as an object
* Move the rectangular prism using a ROS node

**Comment by Cruiz102** [comment]
What is the current status for this issue?

**Comment by AngelCIICMorales** [comment]
I completed this task but forgot to close it.
