### ISSUE TITLE
Test controller.py motor control system

### ISSUE THREAD

**Issue by JuanDelPueblo** [Rumarino-Team/hydrus-software-stack#22]
A key component of the mission logic system is the controls system, which works using a coordinate-based system. A system has already been developed, however it is unknown if it will function correctly or not. Therefore, it is required to find a way to test it, either via a simulation or a node that receives the input and returns an output.

Requirements:
* Create a ROS node which receives inputs from the controller.py node and returns the expected output.
* Fix any bugs that may come up in the controller.py node while testing.

**Comment by AngelCIICMorales** [comment]
I completed the task on another pull request.
